server:
  port: 9999
spring:
  resources:
    static-locations: classpath:static/
  redis:
    host: 120.78.140.235
    port: 6379
    password: redis001
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-idle: 0
        max-wait: -1
  datasource:
    url: jdbc:mysql://120.78.140.235:3306/mytest
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xiaoxingxing
    type: com.alibaba.druid.pool.DruidDataSource #连接池的类型
redisson:
  address: redis://120.78.140.235:6379
  password: redis001